'use strict';

// The МСТ form: step 1 (МСТ / МСТ Premium, country, amount, dates, tourists, purpose, sport, age of each tourist),
// the student document, manual entry of a tourist (Latin + Cyrillic names, passport) and «Создать полис» before
// printing. What every product shares is in src/insurance/flow.js.

const os = require('os');
const path = require('path');
const fs = require('fs-extra');
const PDFDocument = require('pdfkit');
const { PurchaseFlow, FlowError, parseMoney } = require('../insurance/flow');
const { touristsLabel, ruDate } = require('./cases');

// ---------- the MST form ----------

// «Студенты» needs a student document on step 1: a one-page test PDF made on the fly
async function studentDocument() {
  const file = path.join(os.tmpdir(), 'qa-mst-student-document.pdf');
  if (await fs.pathExists(file)) return file;
  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4' });
    const out = fs.createWriteStream(file);
    out.on('finish', resolve).on('error', reject);
    doc.pipe(out);
    doc.fontSize(18).text('STUDENT CERTIFICATE (TEST DOCUMENT)', { align: 'center' }).moveDown();
    doc.fontSize(12).text('Generated by QA AI Agent for automated testing on dev. Not a real document.');
    doc.end();
  });
  return file;
}

class MstFlow extends PurchaseFlow {
  constructor(browser) {
    super(browser, { product: 'mst' });
  }

  async selectParams(c) {
    const page = this.page;
    if (c.variant === 'premium') {
      await this.withPreview(() => page.getByText(/^МСТ PREMIUM$/).first().click({ force: true }));
      await page.waitForTimeout(800);
    }
    // country: a long list — click the option by its exact name
    await page.getByText('Выберите страны', { exact: true }).first().click();
    const option = page.getByText(c.country.label, { exact: true }).last();
    await option.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {
      throw new FlowError('step1', `в списке стран нет «${c.country.label}»`);
    });
    await this.withPreview(() => option.click());
    await page.keyboard.press('Escape').catch(() => {});
    await this.pick('Страховая сумма', c.amount.label);
    const dates = page.locator('input[placeholder="дд.мм.гггг — дд.мм.гггг"]');
    await this.withPreview(async () => {
      await dates.click();
      await dates.pressSequentially(`${ruDate(c.startDate)}${ruDate(c.endDate)}`, { delay: 30 });
      await dates.press('Escape');
    });
    await this.pick('Туристы', touristsLabel(c.count));
    await this.pick('Цель поездки', c.purposeLabel);
    if (c.purpose === 'student') await this.uploadStudentDocument();
    if (c.sport) {
      await this.pick('Вид спорта', c.sport.label);
      await this.pick('Уровень спорта', c.level.label);
    }
    for (let i = 1; i <= c.count; i++) await this.pick(`Турист ${i}`, c.ageLabel);
    await this.settle();
    return this.readStep1();
  }

  async uploadStudentDocument() {
    const page = this.page;
    const input = page.locator('input[type="file"]').first();
    await input.setInputFiles(await studentDocument()).catch((e) => {
      throw new FlowError('step1', `не удалось приложить студенческий документ: ${e.message.split('\n')[0]}`);
    });
    // accepted when the «Загрузите студенческий документ» hint goes away
    const hint = page.getByText('Загрузите студенческий документ');
    const ok = await hint.waitFor({ state: 'hidden', timeout: 20000 }).then(() => true, () => false);
    if (!ok) throw new FlowError('step1', 'студенческий документ не принят формой за 20 с');
  }

  async readStep1() {
    const t = await this.text();
    const preview = this.monitor.lastPreview();
    return {
      premium: parseMoney((/Предварительный расчет на[^\n]*\n+\s*([\d\s ]+₸)/.exec(t) || [])[1]),
      request: preview && preview.request,
      calcTotal: preview && preview.body && preview.body.data ? preview.body.data.total_premium : null,
      calcStatus: preview && preview.status,
      banner: await this.bannerErrors(),
    };
  }

  // Manual tourist entry: Latin names as in the passport, Cyrillic names, birth date, passport
  async fillManual(person) {
    const page = this.page;
    this.monitor.step('manual-entry');
    const modal = this.clientModal();
    const manualBtn = modal.locator('button', { hasText: 'Заполнить данные вручную' });
    if (await manualBtn.isVisible().catch(() => false)) await manualBtn.click();
    await page.waitForTimeout(800);

    // Field order on dev: last/first name Latin, last/first name Cyrillic, birth date, passport number, issue date
    const inputs = modal.locator('input');
    const values = [person.lastNameLatin, person.firstNameLatin, person.lastName, person.firstName, ruDate(person.birthDate), person.docNumber, ruDate(person.docDate)];
    for (const [i, v] of values.entries()) await inputs.nth(i).fill(v);

    const choose = async (value) => {
      const trigger = modal.locator('button', { hasText: 'Выберите из списка' }).first();
      if (!(await trigger.isVisible().catch(() => false))) return null;
      await trigger.click();
      await page.waitForTimeout(300);
      const opt = page.getByText(value, { exact: true }).last();
      if (!(await opt.isVisible().catch(() => false))) {
        await page.keyboard.press('Escape').catch(() => {});
        return null;
      }
      await opt.click();
      await page.waitForTimeout(300);
      return value;
    };
    const gender = await choose(person.gender === 'female' ? 'Женский' : 'Мужской');
    const docType = await choose('Паспорт');
    // «Кем выдан»: the input under the label «Укажите, кем выдан»
    const marked = await modal.evaluate((root) => {
      const label = [...root.querySelectorAll('*')].find((e) => !e.children.length && e.textContent.trim() === 'Укажите, кем выдан');
      for (let p = label && label.parentElement; p; p = p.parentElement) {
        const input = p.querySelector('input');
        if (input) { input.setAttribute('data-qa', 'issued-by'); return true; }
      }
      return false;
    }).catch(() => false);
    if (marked) await modal.locator('input[data-qa=issued-by]').fill('МВД РК');

    const confirm = await this.confirmClientModal();
    return { ...confirm, gender, docType };
  }

  // MST step 3 first saves the policy («Создать полис»), then «Выписать» opens the print window
  async openPrintModal(printModal) {
    const page = this.page;
    await page.locator('button:visible', { hasText: /^Создать полис$/ }).first().click();
    const issueBtn = page.locator('button:visible', { hasText: /^Выписать$/ }).last();
    await issueBtn.waitFor({ state: 'visible', timeout: 25000 }).catch(() => {
      throw new FlowError('anketa', 'после «Создать полис» не появилась кнопка «Выписать»');
    });
    // e.g. «Студенты»: «…полис с целью «учёба» отсюда выписать пока нельзя» and the button stays disabled
    // the button turns active a few seconds after the draft is saved — blocked only if it stays disabled
    const enabled = await page.waitForFunction((el) => el && !el.disabled, await issueBtn.elementHandle(), { timeout: 15000 })
      .then(() => true, () => false);
    if (!enabled) {
      const t = await this.text();
      this.issueBlocked = (t.split('\n').map((l) => l.trim()).find((l) => /нельзя|невозможно|недоступ/i.test(l))) || 'кнопка «Выписать» неактивна';
      return false;
    }
    await issueBtn.click();
    await printModal.waitFor({ state: 'visible', timeout: 15000 }).catch(() => {
      throw new FlowError('anketa', 'после «Выписать» не открылось окно «Печать анкеты»');
    });
  }
}

module.exports = { MstFlow };
